nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin:
            - '%env(CORS_ALLOW_ORIGIN)%'
        allow_methods: ['GET', 'POST', 'DELETE', 'PATCH', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        allow_credentials: false
        max_age: 3600
    paths:
        '^/api/':
            origin_regex: false
            allow_origin:
                - '%env(CORS_ALLOW_ORIGIN)%'
            allow_methods: ['GET', 'POST', 'DELETE', 'PATCH', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
