parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'

    App\Service\JwtService:
        arguments:
            $secret: '%env(JWT_SECRET)%'

    App\Service\FileUploadService:
        arguments:
            $projectDir: '%kernel.project_dir%'
    
    App\EventListener\JwtAuthListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: 10 }
